### PR TITLE
Typescript migration

### PR DESCRIPTION
**Pull request by Helmoz**
# :white_check_mark: store :floppy_disk:
- [x] [entities](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/store/entities.ts) - **_imp:_** d71a8e2
- [x] [grid](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/store/grid.js) - **_imp:_** f74b960
- [x] [menu](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/store/menu.ts) - **_imp:_** 4a818c4
- [x] [properties](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/store/properties.js) - **_imp:_** 4e33fd8
- [x] [types](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/store/types.ts) - **_imp:_** 4a818c4
- [x] [users](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/store/users.ts) - **_imp:_** 5e92d29
 
# :white_check_mark: pages :page_with_curl:
- [x] registries
     - [x] [/_typeName/index](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/pages/registries/_typeName/index.vue) - **_imp:_** d71a8e2
          - [x] [/_id/index](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/pages/registries/_typeName/_id/index.vue) - **_imp:_** 4e33fd8
- [x] [authentication](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/pages/authentication.vue) - **_imp:_** d6b86e3 
- [x] [index](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/pages/index.vue) - **_imp:_** 0978505
- [x] [registries](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/pages/registries.vue) - **_imp:_** 0978505

# :white_check_mark: components :open_file_folder:
- [x] authentication
     - [x] [authentication-card](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/Authentication/authentication-card.vue) - **_imp:_** 8bfbf7c
     - [x] [login](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/Authentication/login.vue) - **_imp:_** 8bfbf7c
     - [x] [password-field](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/Authentication/password-field.vue) - **_imp:_** 8bfbf7c
     - [x] [signup](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/Authentication/signup.vue) - **_imp:_** 8bfbf7c
     - [x] [username-field](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/Authentication/username-field.vue) - **_imp:_** 8bfbf7c
- [x] menu
     - [x] [list-tile](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/menu/list-tile.vue) - **_imp:_** 9c0441f
     - [x] [new-item-dialog](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/menu/new-item-dialog.vue) - **_imp:_** 9c0441f
     - [x] [user-profile](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/menu/user-profile.vue) - **_imp:_** 9c0441f
- [x] property
     - [x] [complex-property](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/property/complex-property.vue) - **_imp:_** deaca9c
     - [x] [edit-dialog](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/property/edit-dialog.vue) - **_imp:_** 9c3a42e
     - [x] [grid-row](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/property/grid-row.vue) - **_imp:_** 9c3a42e
     - [x] [new-dialog](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/property/new-dialog.vue) - **_imp:_** deaca9c
     - [x] [simple-property](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/property/simple-property.vue) - **_imp:_** deaca9c
- [x] registry
     - [x] new
          - [x] [entity-dialog](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/registry/new/entity-dialog.vue) - **_imp:_** 1c88461
          - [x] [type-dialog](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/registry/new/type-dialog.vue) - **_imp:_** 1c88461
     - [x] [grid-row](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/registry/grid-row.vue) - **_imp:_** 1c88461
     - [x] [navigation-drawer](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/registry/navigation-drawer.vue) - **_imp:_** 1c88461
     - [x] [type-list-tile](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/registry/type-list-tile.vue) - **_imp:_** 1c88461
- [x] [delete-dialog](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/delete-dialog.vue) - **_imp:_** 860e8f4
- [x] [grid](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/grid.vue) - **_imp:_** a462fc4
- [x] [toolbar](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/components/toolbar.vue) - **_imp:_** a462fc4

# :white_check_mark: layouts :clipboard:
- [x] [default](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/layouts/default.vue) - **_imp:_** 0978505

# :white_check_mark: middleware :rocket:
- [x] [authentication](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/middleware/authentication.js) - **_imp:_** 693694c
- [x] [loadMenuItems](https://github.com/itis-anete/InfoSystem/blob/typescript/InfoSystem.Web/ClientApp/middleware/loadMenuItems.js) - **_imp:_** 693694c

### CODE REVIEW

**Review by Halloneo — APPROVED** [review]
Typescript is better than JS

**Review by Halloneo — APPROVED** [review]
Typescript is still better than JS

**Review by Helmoz — COMMENTED** [review]
Тут сыглы

**Review by d4n0n-myself — APPROVED** [review]
Заебумба

**Pull request merged**
